name: pay_check
description: A Flutter app for shared payment tracking.
version: 1.0.1+3

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  intl: ^0.20.2
  uuid: ^3.0.7
  image_picker: ^1.0.4
  path_provider: ^2.0.12
  equatable: ^2.0.7
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.2
  multi_dropdown:
    path: packages/multi_dropdown
  shared_preferences: ^2.2.2
  photo_manager: ^3.0.0
  photo_manager_image_provider: ^2.0.0
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/mother.png
    - assets/images/father.png
    - assets/images/children.png
    - assets/icons/person_icon_01.png
    - assets/icons/person_icon_02.png
    - assets/icons/person_icon_03.png
    - assets/icons/person_icon_04.png
    - assets/icons/person_icon_05.png
    - assets/icons/person_icon_06.png
    - assets/icons/person_icon_07.png
    - assets/icons/person_icon_08.png
    - assets/icons/app_icon.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/app_icon.png
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    image: assets/icons/app_icon.png
  web: false
